// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  wiki: [
    'wiki/README',
    {
      type: 'autogenerated',
      dirName: 'wiki',
    },
  ],
  playbooks: [
    {
      type: 'autogenerated',
      dirName: 'playbooks',
    },
  ],
};

module.exports = sidebars;
